import { Readable } from 'svelte/store';
export declare const __table: import("svelte/store").Writable<any[]>;
export declare const __columns: Readable<any>;
export declare const __columns__data: Readable<any>;
export declare const __offsets__column: Readable<any>;
export declare const __domain__table: import("svelte/store").Writable<number[]>;
export declare const __domain__ticks: import("svelte/store").Writable<number[]>;
export declare const __rows: Readable<unknown>;
export declare const __rows__data: Readable<false | "" | 0 | any[]>;
export declare const __reverse__columns: Readable<any>;
export declare const __rank__table: Readable<unknown>;
export declare const __row_id: import("svelte/store").Writable<any>;
export declare const __inputs__filter__rows__data: import("svelte/store").Writable<any>;
export declare const __filter__rows__data: Readable<false | "" | 0 | any[]>;
export declare const __table__filter__rows__data: Readable<any>;
export declare const __highlight__rows__data: import("svelte/store").Writable<any>;
export declare const __table__highlight__rows__data: import("svelte/store").Writable<any>;
export declare const __row: import("svelte/store").Writable<any>;
export declare function set__row(): void;
